/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.ururu.libclang.examples;

import ru.urururu.clang.*;

public class App {
    public static void main(String[] args) {
        SWIGTYPE_p_void index = libclang.clang_createIndex(0, 0);
        try {
            SWIGTYPE_p_CXTranslationUnitImpl unit = libclang.clang_parseTranslationUnit(index, "header.hpp", null, 0,
                    null, 0, CXTranslationUnit_Flags.CXTranslationUnit_None.swigValue());
            if (unit == null) {
                System.err.println("Unable to parse translation unit. Quitting.");
                System.exit(-1);
            }

            CXCursor cursor = libclang.clang_getTranslationUnitCursor(unit);

            CXCursorKind cxCursorKind = libclang.clang_getCursorKind(cursor);
            System.out.println("cxCursorKind = " + cxCursorKind);

            libclang.clang_disposeTranslationUnit(unit);
        } finally {
            libclang.clang_disposeIndex(index);
        }
    }
}
