/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.ururu.libclang.examples;

import ru.urururu.clang.*;

public class App {
    public static void main(String[] args) {
        SWIGTYPE_p_void index = libclang.clang_createIndex(0, 0);
        try {
            SWIGTYPE_p_CXTranslationUnitImpl unit = libclang.clang_parseTranslationUnit(index, "header.hpp", null, 0,
                    null, 0, CXTranslationUnit_Flags.CXTranslationUnit_None.swigValue());
            if (unit == null) {
                System.err.println("Unable to parse translation unit. Quitting.");
                System.exit(-1);
            }

            CXCursor cursor = libclang.clang_getTranslationUnitCursor(unit);

            clang_visitChildren(cursor, (CXCursor c, CXCursor parent, SWIGTYPE_p_void client_data) -> {
                System.out.println("Cursor '" + libclang.clang_getCursorSpelling(c) + "' of kind '"
                        + libclang.clang_getCursorKindSpelling(libclang.clang_getCursorKind(c)));
                return CXChildVisitResult.CXChildVisit_Recurse;
            }, null);

            libclang.clang_disposeTranslationUnit(unit);
        } finally {
            libclang.clang_disposeIndex(index);
        }
    }

    // todo remove
    static long clang_visitChildren(CXCursor parent, CXCursorVisitor visitor, SWIGTYPE_p_void client_data) {
        return libclang.clang_visitChildren(parent, null, client_data);
    }

    // todo add to lib
    @FunctionalInterface
    interface CXCursorVisitor {
        CXChildVisitResult apply(CXCursor cursor, CXCursor parent, SWIGTYPE_p_void clientData);
    }
}
